### ISSUE TITLE
Definition Attention mechanism

### ISSUE THREAD

**Issue by helpmefindaname** [sebastian-hofstaetter/teaching#1]
Referring to the explanation of the attention mechanism in [Neural Networks for NLP slide 41](https://github.com/sebastian-hofstaetter/teaching/blob/master/advanced-information-retrieval/lectures/Lecture%204%20-%20Neural%20Networks%20for%20NLP.pdf) 

The phrase "the attention mechanism is defined as" suggests that this is the one and only definition of attention, however there are many attention mechanisms. The effect from some is evaluated [here](https://arxiv.org/abs/1703.03906).
I'd suggesting rephrasing it to "additive attention is defined as" as that's the commonly used name for the type of attention on that slide, or to describe the mechanism more general by declaring 
<img src="https://render.githubusercontent.com/render/math?math=\overline{a}^j_{[i] } =f(t_j, s_j ) "> and noting that one example is 
<img src="https://render.githubusercontent.com/render/math?math=f(t_j,%20s_j)%20=%20v%20%20tan([t_j%3Bs_j]U%2Bb)">

**Comment by sebastian-hofstaetter** [comment]
Hi,
Thank you very much for the comment - i fixed the slides (I'll update them here once the lecture took place, because i'll move a couple of things around)

Don't forget to mention this at the exercise interview for bonus points :) and keep the suggestions coming!

Best,
Sebastian
