### ISSUE TITLE
How to cite this lecture?

### ISSUE THREAD

**Issue by carlesoctav** [sebastian-hofstaetter/teaching#147]
Is there a BibTeX entry that I can use to cite this lecture? Thanks in advance.

**Comment by sebastian-hofstaetter** [comment]
hey, thanks for wanting to cite us :) 
if you can please cite: 

A Time-Optimized Content Creation Workflow for Remote Teaching Sebastian Hofstätter, Sophia Althammer, Mete Sertkan and Allan Hanbury https://arxiv.org/abs/2110.05601

thank you 💯
