### ISSUE TITLE
AIR'21 - Lecture 2 Fix closed captions

### ISSUE THREAD

**Issue by sebastian-hofstaetter** [sebastian-hofstaetter/teaching#15]
This is the coordination issue for fixing the closed captions of Lecture 2: https://github.com/sebastian-hofstaetter/teaching/blob/master/advanced-information-retrieval/Lecture%202%20-%20Closed%20Captions.md

If you want to fix errors, please leave a short comment here before starting to block the issue. Thanks!

**Comment by hudcondr** [comment]
I would take this one - 11919907

**Comment by sebastian-hofstaetter** [comment]
Cool 👍!

**Comment by sebastian-hofstaetter** [comment]
Pull request #16 was merged super quickly, so the task is open again if someone wants take another pass :) (just leave a short comment here again)

**Comment by sebastian-hofstaetter** [comment]
Perfect - I think the text is pretty good now, therefore closing the issue.
