### ISSUE TITLE
AIR'21 - Lecture 3 Fix closed captions

### ISSUE THREAD

**Issue by sebastian-hofstaetter** [sebastian-hofstaetter/teaching#18]
This is the coordination issue for fixing the closed captions of Lecture 2: https://github.com/sebastian-hofstaetter/teaching/blob/master/advanced-information-retrieval/Lecture%203%20-%20Closed%20Captions.md

This time it also missed a couple of titles (i don't know why), please add them as well from the slides. 

If you want to fix errors, please leave a short comment here before starting to block the issue. Thanks!

**Comment by amartzloff** [comment]
I can fix the closed captions for Crash Course IR 3 - Test Collections

**Comment by sebastian-hofstaetter** [comment]
👍 go ahead!

**Comment by sebastian-hofstaetter** [comment]
#19 closes this issue.
