### ISSUE TITLE
Lecture 6 slide 11 citation typo

### ISSUE THREAD

**Issue by WojciechKusa** [sebastian-hofstaetter/teaching#35]
Hey,

One reference on slide 11 for [lecture 6](https://github.com/sebastian-hofstaetter/teaching/blob/master/advanced-information-retrieval/Lecture%206%20-%20Transformer%20and%20BERT%20Pre-training.pdf) has a typo in a year:

- Transformer-XH [Zhao et al., 2014]
Should be [2020](https://openreview.net/pdf?id=r1eIiCNYwS) instead of 2014 

Best, 
Wojtek

**Comment by sebastian-hofstaetter** [comment]
Thanks, I'll fix it for next time!
