### ISSUE TITLE
PowerPoint file

### ISSUE THREAD

**Issue by runningmq** [sebastian-hofstaetter/teaching#41]
hi, It's really awesome and useful learning materials.
But can you support us the PowerPoint files for the lectures PDF files ?

thanks

**Comment by sebastian-hofstaetter** [comment]
Hi,
Unfortunately, because of our workflow the powerpoint files have all the audio attached to them, which makes them quite large and cumbersome to share. That is why we don't publish them. Do you have a specific use case for the powerpoint files (vs. using the pdfs)?
Best,
Sebastian

**Comment by runningmq** [comment]
hi sebastian, 
I'm try to run the tool from ppt to video. It will be great I you supple some sample ppt or ppts without any audio/video.
BTW, I'm also doing some work which can generate teaching video from raw ppt with only text information. I think I can leverage your work and do some experiment to compare with your generated videos(if you can help to supplement some ppts).
Thanks
