### ISSUE TITLE
YouTube AIR Lecture 5: Corrected CC‘s missing

### ISSUE THREAD

**Issue by e8725144** [sebastian-hofstaetter/teaching#44]
Only the generated captions are available in the video.

**Comment by sebastian-hofstaetter** [comment]
Thanks for flagging this, I added them. 
Best,
Sebastian

**Comment by akrlowicz** [comment]
Hello,
I spotted some minor mistake in CCs for first slide and typo "wamt" in 39th slide

**Comment by sebastian-hofstaetter** [comment]
Hi,
If you want you could fix them here https://github.com/sebastian-hofstaetter/teaching/blob/master/advanced-information-retrieval/Lecture%205%20-%20Closed%20Captions.md and make a pull request, and after that i could merge them into the youtube ccs as well. Thanks!
